--
-- Copyright (c) 2010-2025 Evolveum and contributors
--
-- Licensed under the EUPL-1.2 or later.
--
 
CREATE TYPE ApplicationLifecycleType AS ENUM (
	'REQUESTED',
	'IN_REVIEW',
	'ACTIVE',
	'WITH_ERROR'
);

CREATE TYPE ApplicationTagType AS ENUM (
	'DEPLOYMENT',
	'LOCALITY',
	'CATEGORY',
	'COMMON'
);

CREATE TYPE FrameworkType AS ENUM (
	'JAVA_BASED',
	'LOW_CODE'
);

CREATE TYPE LicenseType AS ENUM (
	'MIT',
	'APACHE_2',
	'BSD',
	'EUPL'
);

CREATE TYPE LifecycleType AS ENUM (
	'IN_REVIEW',
	'ACTIVE',
	'DEPRECATED',
	'ARCHIVED',
	'WITH_ERROR'
);

CREATE TYPE BuildFrameworkType AS ENUM (
	'MAVEN',
	'GRADLE'
);

CREATE TYPE GlobalityType AS ENUM (
	'GLOBAL',
	'SPECIFIC'
);

CREATE TYPE "CapabilityType" AS ENUM (
	'CREATE',
	'GET',
	'UPDATE',
	'DELETE',
	'TEST',
	'SCRIPT_ON_CONNECTOR',
	'SCRIPT_ON_RESOURCE',
	'AUTHENTICATION',
	'SEARCH',
	'VALIDATE',
	'SYNC',
	'LIVE_SYNC',
	'SCHEMA',
	'DISCOVER_CONFIGURATION',
	'RESOLVE_USERNAME',
	'PARTIAL_SCHEMA',
	'COMPLEX_UPDATE_DELTA',
	'UPDATE_DELTA'
);
-- end of region

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

SET default_tablespace = '';

SET default_table_access_method = heap;

-- region ID-pool table

CREATE TABLE application (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	name character varying(255),
	display_name character varying(255),
	description character varying(255),
	lifecycle_state ApplicationLifecycleType NOT NULL,
	created_at timestamp without time zone NOT NULL,
	updated timestamp without time zone NOT NULL,
	logo_path character varying(255)
);

CREATE TABLE application_tag (
	id integer NOT NULL,
	name character varying(255) NOT NULL,
	display_name character varying(255) NOT NULL,
	tag_type ApplicationTagType NOT NULL
);

ALTER TABLE application_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME application_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE application_application_tag (
    id bigint NOT NULL,
    application_id uuid NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE application_application_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME application_application_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE application_origin (
    id bigint NOT NULL,
    application_id uuid NOT NULL,
    country_id integer NOT NULL
);

ALTER TABLE application_origin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME application_origin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE country_of_origin (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL
);

ALTER TABLE country_of_origin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME country_of_origin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connector (
	id integer NOT NULL,
	revision character varying(255),
	author character varying(255),	
	maintainer character varying(255),
	created_at timestamp without time zone NOT NULL,
	updated timestamp without time zone NOT NULL,
	display_name character varying(255),
	fully_qualified_class_name character varying(255),
	connector_bundle_id integer NOT NULL,
	description text
);

ALTER TABLE connector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connector_tag (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL
);

ALTER TABLE connector_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connector_connector_tag (
    id integer NOT NULL,
    connector_id integer NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE connector_connector_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_connector_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connector_version (
	id integer NOT NULL,
	revision character varying(255),
	author character varying(255),
	maintainer character varying(255),
	created_at timestamp without time zone NOT NULL,
	updated timestamp without time zone NOT NULL,
	lifecycle_state LifecycleType NOT NULL,
	connector_bundle_version_id integer,
	connector_bundle_version_revision character varying(255),
	connector_id integer,
	fully_qualified_class_name character varying(255)
);

ALTER TABLE connector_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connector_bundle (
	id integer NOT NULL,
	revision character varying(255),
	author character varying(255),
	maintainer character varying(255),
	created_at timestamp without time zone NOT NULL,
	updated timestamp without time zone NOT NULL,
	lifecycle_state LifecycleType NOT NULL,
	bundle_name character varying(255),
	display_name character varying(255),
	description text,
	framework FrameworkType NOT NULL,
	license LicenseType NOT NULL,
	ticketing_link  character varying(255),
	project_homepage character varying(255),
	git_clone_ULR character varying(255),
	path_to_project character varying(255),
	build_framework BuildFrameworkType
);

ALTER TABLE connector_bundle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_bundle_id_seq
    START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1
);

CREATE TABLE connector_bundle_version (
	id integer NOT NULL,
	revision character varying(255),
	author character varying(255),
	maintainer character varying(255),
	created_at timestamp without time zone NOT NULL,
	updated timestamp without time zone NOT NULL,
	lifecycle_state LifecycleType NOT NULL,
	connector_bundle_id integer,
	bundle_version character varying(255),
	browse_link character varying(255),
	git_clone_ULR character varying(255),
	path_to_project character varying(255),
	build_framework BuildFrameworkType,
	commit_tag character varying(255)
);

ALTER TABLE connector_bundle_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_bundle_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE download (
    id integer NOT NULL,
    connector_bundle_version_id integer NOT NULL,
	connector_bundle_version_revision character varying(255) NOT NULL,
    ip_address character varying(45) NOT NULL,
    user_agent character varying(255) NOT NULL,
    downloaded_at timestamp without time zone NOT NULL
);

ALTER TABLE download ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME download_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE request (
    id integer NOT NULL,
    application_id uuid NOT NULL,
    requester character varying(255),
    mail character varying(50),
    collab boolean NOT NULL,
    base_url character varying(255),
    system_version character varying(20),
    CONSTRAINT unique_request_per_application UNIQUE (application_id)
);

ALTER TABLE request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE object_class_capabilities (
    id integer NOT NULL,
    request_id integer NOT NULL,
    object_name character varying(30) NOT NULL,
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[] NOT NULL
);

ALTER TABLE object_class_capabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME object_class_capabilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE vote (
    request_id integer NOT NULL,
    voter character varying(255) NOT NULL
);

CREATE TABLE integration_method (
	id UUID DEFAULT gen_random_uuid(),
	application_id uuid NOT NULL,
	display_name character varying(255),
	description character varying(255),
	tutorial text,
	file_path character varying(255),
	midpoint_minVersion integer,
	midpoint_maxVersion integer,
	lifecycle_state LifecycleType NOT NULL,
	revision character varying(255),
	author character varying(255),	
	maintainer character varying(255),
	created_at timestamp without time zone NOT NULL,
	updated timestamp without time zone NOT NULL,
	app_version character varying(255)
);

CREATE TABLE integration_method_type (
	id integer NOT NULL,
    display_name character varying(255) NOT NULL,
    description text
);

ALTER TABLE integration_method_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME integration_method_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE int_method_int_method_type (
    id integer NOT NULL,
    integration_method_id UUID NOT NULL, 
	integration_method_revision character varying(255) NOT NULL,
    integration_method_type_id integer NOT NULL
);

ALTER TABLE int_method_int_method_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME int_method_int_method_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE capability (
	id integer NOT NULL,
	name character varying(255),
	description text,
	display_order integer,
	globality GlobalityType NOT NULL
);

ALTER TABLE capability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME capability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE integration_method_capability (
	id integer NOT NULL,
	object_class character varying(255) NOT NULL,
	integ_method_id uuid,
	integ_method_revision character varying(255)
);

ALTER TABLE integration_method_capability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME integration_method_capability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE integration_method_capability_item (
	integration_method_capability_id integer NOT NULL,
	capability_id integer NOT NULL
);

CREATE TABLE conn_version_capability (
	id integer NOT NULL,
	object_class character varying(255) NOT NULL,
	conn_version_id integer,
	conn_version_revision character varying(255)
);

ALTER TABLE conn_version_capability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME conn_version_capability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE conn_version_capability_item (
    conn_version_capability_id integer NOT NULL,
    capability_id integer NOT NULL
);

CREATE TABLE integration_method_connector (
    id integer NOT NULL,
    integ_method_id uuid NOT NULL,
    integ_method_revision character varying(255) NOT NULL,
    connector_id integer NOT NULL,
    connector_minVersion character varying(255) NOT NULL,
    connector_maxVersion character varying(255)
);

ALTER TABLE integration_method_connector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME integration_method_connector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE recently_used_applications (
    id             bigint NOT NULL,
    user_id        character varying(255) NOT NULL,
    application_id uuid NOT NULL
);

ALTER TABLE recently_used_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recently_used_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE organizations (
    id          integer NOT NULL,
    name        character varying(255) NOT NULL,
    description text
);

ALTER TABLE organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog_users (
    username        character varying(255) NOT NULL,
    password        character varying(255) NOT NULL,
    role            character varying(64)  NOT NULL,
    organization_id integer
);

CREATE TABLE midpoint_version (
    id integer NOT NULL,
    version character varying(64),
    version_name character varying(64),
    is_current boolean NOT NULL DEFAULT false
);

ALTER TABLE midpoint_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME midpoint_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
-- end of region

-- region tables CONSTRAINTs

ALTER TABLE ONLY application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application_tag
    ADD CONSTRAINT application_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT application_application_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT application_origin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY country_of_origin
    ADD CONSTRAINT country_of_origin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY connector
    ADD CONSTRAINT connector_pkey PRIMARY KEY (id);

ALTER TABLE ONLY connector_tag
    ADD CONSTRAINT connector_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY connector_connector_tag
    ADD CONSTRAINT connector_connector_tag_pkey PRIMARY KEY (id);
	
ALTER TABLE ONLY connector_version
    ADD CONSTRAINT connector_version_pkey PRIMARY KEY (id, revision);

ALTER TABLE ONLY connector_bundle
    ADD CONSTRAINT connector_bundle_pkey PRIMARY KEY (id);
	
ALTER TABLE ONLY connector_bundle_version
    ADD CONSTRAINT connector_bundle_version_pkey PRIMARY KEY (id, revision);

ALTER TABLE ONLY download
    ADD CONSTRAINT download_pkey PRIMARY KEY (connector_bundle_version_id, connector_bundle_version_revision, ip_address, downloaded_at);
	
ALTER TABLE ONLY request
    ADD CONSTRAINT request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY object_class_capabilities
    ADD CONSTRAINT object_class_capabilities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY vote
    ADD CONSTRAINT vote_pkey PRIMARY KEY (request_id, voter);
	
ALTER TABLE ONLY integration_method
    ADD CONSTRAINT integration_method_pkey PRIMARY KEY (id, revision);	
	
ALTER TABLE ONLY integration_method_type
    ADD CONSTRAINT integration_method_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY int_method_int_method_type
    ADD CONSTRAINT int_method_int_method_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY capability
    ADD CONSTRAINT capability_pkey PRIMARY KEY (id);

ALTER TABLE ONLY integration_method_capability
    ADD CONSTRAINT integration_method_capability_pkey PRIMARY KEY (id);
	
ALTER TABLE ONLY integration_method_capability_item
    ADD CONSTRAINT int_method_capability_item_pkey PRIMARY KEY (integration_method_capability_id, capability_id);
	
ALTER TABLE ONLY conn_version_capability
    ADD CONSTRAINT conn_version_capability_pkey PRIMARY KEY (id);	
	
ALTER TABLE ONLY conn_version_capability_item
    ADD CONSTRAINT conn_version_capability_item_pkey PRIMARY KEY (conn_version_capability_id, capability_id);
	
ALTER TABLE ONLY integration_method_connector
    ADD CONSTRAINT integration_method_connector_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recently_used_applications
    ADD CONSTRAINT recently_used_applications_pkey PRIMARY KEY (id);
	
ALTER TABLE ONLY organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog_users
    ADD CONSTRAINT catalog_users_pkey PRIMARY KEY (username);
	
ALTER TABLE ONLY midpoint_version
    ADD CONSTRAINT midpoint_version_pkey PRIMARY KEY (id);
	
	
	

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT unique_app_tag UNIQUE (application_id, tag_id);
	
ALTER TABLE ONLY connector
    ADD CONSTRAINT unique_connector UNIQUE (id, revision);	
	
ALTER TABLE ONLY connector_version
    ADD CONSTRAINT unique_connector_version UNIQUE (id, revision);
	
ALTER TABLE ONLY connector_bundle
    ADD CONSTRAINT unique_connector_bundle_id UNIQUE (id, revision);
	
ALTER TABLE ONLY connector_bundle
    ADD CONSTRAINT unique_connector_bundle_bundle_name UNIQUE (bundle_name, revision);
	
ALTER TABLE ONLY connector_bundle_version
    ADD CONSTRAINT unique_connector_bundle_version UNIQUE (bundle_version);
	
ALTER TABLE ONLY integration_method
    ADD CONSTRAINT unique_integration_method UNIQUE (id, revision);	

ALTER TABLE ONLY recently_used_applications
    ADD CONSTRAINT uq_rua_user_app UNIQUE (user_id, application_id);

ALTER TABLE ONLY integration_method_connector
    ADD CONSTRAINT uq_imc_met_id_met_rev UNIQUE (integ_method_id, integ_method_revision);
	
	
	

CREATE INDEX idx_dl_ver 								ON download USING btree (connector_bundle_version_id);
CREATE INDEX IF NOT EXISTS ix_request_capabilities_gin 	ON object_class_capabilities USING gin (capabilities);
CREATE INDEX idx_conn_bundle 							ON connector USING btree (connector_bundle_id);
CREATE INDEX idx_aat_application_id         			ON application_application_tag USING btree (application_id);
CREATE INDEX idx_aat_tag_id                 			ON application_application_tag USING btree (tag_id);
CREATE INDEX idx_app_origin_application_id  			ON application_origin USING btree (application_id);
CREATE INDEX idx_cver_connector_id          			ON connector_version USING btree (connector_id);
CREATE INDEX idx_cver_bundle_version_id    				ON connector_version USING btree (connector_bundle_version_id);
CREATE INDEX idx_cct_connector_id           			ON connector_connector_tag USING btree (connector_id);
CREATE INDEX idx_cct_tag_id                 			ON connector_connector_tag USING btree (tag_id);
CREATE INDEX idx_integ_method_app_id        			ON integration_method USING btree (application_id);
CREATE INDEX idx_imc_connector_id           			ON integration_method_connector USING btree (connector_id);
CREATE INDEX idx_imc_integ_method_id        			ON integration_method_connector USING btree (integ_method_id);
CREATE INDEX idx_im_cap_integ_method_id     			ON integration_method_capability USING btree (integ_method_id);
CREATE INDEX idx_cvc_conn_version_id        			ON conn_version_capability USING btree (conn_version_id);
CREATE INDEX idx_request_application_id     			ON request USING btree (application_id);
CREATE INDEX idx_obj_cap_request_id         			ON object_class_capabilities USING btree (request_id);
CREATE INDEX idx_vote_request_id            			ON vote USING btree (request_id);
CREATE INDEX idx_rua_user_id                			ON recently_used_applications USING btree (user_id);
CREATE INDEX idx_rua_application_id         			ON recently_used_applications USING btree (application_id);
CREATE INDEX idx_catalog_users_org_id       			ON catalog_users USING btree (organization_id);
CREATE INDEX idx_app_lifecycle              			ON application USING btree (lifecycle_state);
CREATE INDEX idx_cbundle_lifecycle          			ON connector_bundle USING btree (lifecycle_state);
CREATE INDEX idx_cbundle_version_lifecycle  			ON connector_bundle_version USING btree (lifecycle_state);
CREATE INDEX idx_cver_lifecycle             			ON connector_version USING btree (lifecycle_state);
CREATE INDEX idx_integ_method_lifecycle     			ON integration_method USING btree (lifecycle_state);
CREATE INDEX idx_app_name                   			ON application USING btree (name);
CREATE INDEX idx_cbundle_name               			ON connector_bundle USING btree (bundle_name);
CREATE INDEX idx_midpoint_version             			ON midpoint_version USING btree (id);
CREATE INDEX idx_imimt_im_id         					ON int_method_int_method_type USING btree (integration_method_id);
CREATE INDEX idx_imimt_imt_id                 			ON int_method_int_method_type USING btree (integration_method_type_id);




ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT fk_app_tag_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT fk_app_tag_tag FOREIGN KEY (tag_id) REFERENCES application_tag(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT fk_app_origin_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT fk_app_origin_country FOREIGN KEY (country_id) REFERENCES country_of_origin(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_method
    ADD CONSTRAINT fk_integ_method_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY connector
    ADD CONSTRAINT fk_conn_conn_bundle FOREIGN KEY (connector_bundle_id) REFERENCES connector_bundle(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY connector_version
    ADD CONSTRAINT fk_conn_version_connector FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY connector_version
    ADD CONSTRAINT fk_conn_version_conn_bundle_version FOREIGN KEY (connector_bundle_version_id, connector_bundle_version_revision) REFERENCES connector_bundle_version(id, revision) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY connector_bundle_version
    ADD CONSTRAINT fk_conn_version_bundle_conn_bundle FOREIGN KEY (connector_bundle_id) REFERENCES connector_bundle(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY connector_connector_tag
    ADD CONSTRAINT fk_conn_tag_conn FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY connector_connector_tag
    ADD CONSTRAINT fk_conn_tag_tag FOREIGN KEY (tag_id) REFERENCES connector_tag(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_method_connector
    ADD CONSTRAINT fk_int_meth_conn_conn FOREIGN KEY (connector_id) REFERENCES connector(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_method_connector
    ADD CONSTRAINT fk_int_meth_conn_int_meth FOREIGN KEY (integ_method_id, integ_method_revision) REFERENCES integration_method(id, revision) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY recently_used_applications
    ADD CONSTRAINT fk_rua_application FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog_users
    ADD CONSTRAINT fk_catalog_users_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE only integration_method_capability
	ADD CONSTRAINT fk_int_method_capability_int_method FOREIGN KEY (integ_method_id, integ_method_revision) REFERENCES integration_method (id, revision) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE only integration_method_capability_item
    ADD CONSTRAINT fk_imci_group FOREIGN KEY (integration_method_capability_id) REFERENCES integration_method_capability(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE only integration_method_capability_item
    ADD CONSTRAINT fk_imci_capability FOREIGN KEY (capability_id) REFERENCES capability(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE only conn_version_capability_item
    ADD CONSTRAINT fk_cvci_group FOREIGN KEY (conn_version_capability_id) REFERENCES conn_version_capability(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE only conn_version_capability_item
    ADD CONSTRAINT fk_cvci_capability FOREIGN KEY (capability_id) REFERENCES capability(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
	
ALTER TABLE only conn_version_capability
	ADD CONSTRAINT fk_conn_version_capability_conn_version_id_revision FOREIGN KEY (conn_version_id, conn_version_revision) REFERENCES connector_version (id, revision) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
	
ALTER TABLE ONLY request
    ADD CONSTRAINT fk_request_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY object_class_capabilities
    ADD CONSTRAINT fk_objcap_request FOREIGN KEY (request_id) REFERENCES request(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY vote
    ADD CONSTRAINT fk_vote_request FOREIGN KEY (request_id) REFERENCES request(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY download
    ADD CONSTRAINT fk_dl_conn_bun_ver FOREIGN KEY (connector_bundle_version_id, connector_bundle_version_revision) REFERENCES connector_bundle_version(id, revision) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_method
    ADD CONSTRAINT fk_int_meth_mid_min_version FOREIGN KEY (midpoint_minVersion) REFERENCES midpoint_version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
	
ALTER TABLE ONLY integration_method
    ADD CONSTRAINT fk_int_meth_mid_max_version FOREIGN KEY (midpoint_maxVersion) REFERENCES midpoint_version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
	
ALTER TABLE ONLY int_method_int_method_type
    ADD CONSTRAINT fk_im_imt_im FOREIGN KEY (integration_method_id, integration_method_revision) REFERENCES integration_method(id, revision) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY int_method_int_method_type
    ADD CONSTRAINT fk_im_imt_imt FOREIGN KEY (integration_method_type_id) REFERENCES integration_method_type(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
-- end of region