--
-- Copyright (c) 2010-2025 Evolveum and contributors
--
-- Licensed under the EUPL-1.2 or later.
--
 
CREATE TYPE ApplicationLifecycleType AS ENUM (
	'REQUESTED',
	'IN_REVIEW',
	'ACTIVE',
	'WITH_ERROR'
);

CREATE TYPE ApplicationTagType AS ENUM (
	'DEPLOYMENT',
	'LOCALITY',
	'CATEGORY',
	'COMMON'
);

CREATE TYPE FrameworkType AS ENUM (
	'JAVA_BASED',
	'LOW_CODE'
);

CREATE TYPE LicenseType AS ENUM (
	'MIT',
	'APACHE_2',
	'BSD',
	'EUPL'
);

CREATE TYPE ImplementationVersionLifecycleType AS ENUM (
	'IN_REVIEW',
	'ACTIVE',
	'DEPRECATED',
	'ARCHIVED',
	'WITH_ERROR'
);

CREATE TYPE BuildFrameworkType AS ENUM (
	'MAVEN',
	'GRADLE'
);

CREATE TYPE "CapabilityType" AS ENUM (
    'CREATE',
	'GET',
	'UPDATE',
	'DELETE',
	'TEST',
	'SCRIPT_ON_CONNECTOR',
	'SCRIPT_ON_RESOURCE',
	'AUTHENTICATION',
	'SEARCH',
	'VALIDATE',
	'SYNC',
	'LIVE_SYNC',
	'SCHEMA',
	'DISCOVER_CONFIGURATION',
	'RESOLVE_USERNAME',
	'PARTIAL_SCHEMA',
	'COMPLEX_UPDATE_DELTA',
	'UPDATE_DELTA'
);
CREATE TYPE IntegrationMethodType AS ENUM (
    'SCIM',
    'REST_API',
    'OPEN_LDAP',
    'MANUAL_ITSM',
    'DATABASE',
    'CSV'
);
-- end of region

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

SET default_tablespace = '';

SET default_table_access_method = heap;

-- region ID-pool table

CREATE TABLE application (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	name character varying(255),
	display_name character varying(255),
	description character varying(255),
	lifecycle_state ApplicationLifecycleType NOT NULL,
	created_at timestamp without time zone NOT NULL,
	last_modified timestamp without time zone NOT NULL,
	logo_path character varying(255),
	logo_content_type character varying(100),
	logo_original_name character varying(255),
	logo_size_bytes bigint
);

CREATE TABLE application_application_tag (
    id bigint NOT NULL,
    application_id uuid NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE application_application_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME application_application_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE application_origin (
    id bigint NOT NULL,
    application_id uuid NOT NULL,
    country_id integer NOT NULL
);

ALTER TABLE application_origin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME application_origin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE application_tag (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL,
    tag_type ApplicationTagType NOT NULL
);

ALTER TABLE application_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME application_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connid_version (
    version character varying(64) NOT NULL,
    midpoint_version character varying(255) NOT NULL
);

CREATE TABLE country_of_origin (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL
);

ALTER TABLE country_of_origin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME country_of_origin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE downloads (
    implementation_version_id uuid NOT NULL,
    ip_address character varying(45) NOT NULL,
    user_agent character varying(255) NOT NULL,
    downloaded_at timestamp without time zone NOT NULL,
    id uuid NOT NULL
);

CREATE TABLE implementation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name character varying(255),
    connector_bundle_id integer NOT NULL,
    application_id uuid NOT NULL
);

CREATE TABLE implementation_implementation_tag (
    id integer NOT NULL,
    implementation_id uuid NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE implementation_implementation_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME implementation_implementation_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE implementation_tag (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL
);

ALTER TABLE implementation_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME implementation_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE connector_bundle (
    id integer NOT NULL,
    bundle_name character varying(255) UNIQUE,
    maintainer character varying(255),
    framework FrameworkType NOT NULL,
    license LicenseType NOT NULL,
    ticketing_system_link text
);

ALTER TABLE connector_bundle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME connector_bundle_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE implementation_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    description character varying(255),
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[],
    system_version character varying(255),
    author character varying(255),
    publish_date timestamp without time zone,
    lifecycle_state ImplementationVersionLifecycleType NOT NULL,
    implementation_id uuid NOT NULL,
    bundle_version_id integer NOT NULL,
    error_message character varying(255),
    class_name character varying(255)
);

CREATE TABLE bundle_version (
    id integer NOT NULL,
    connector_bundle_id integer NOT NULL,
    connector_version character varying(255),
    browse_link character varying(255),
    checkout_link character varying(255),
    download_link character varying(255),
    connid_version character varying(64),
    documentation_link character varying(255),
    link_sample character varying(255),
    released_date date,
    build_framework BuildFrameworkType NOT NULL,
    path_to_project text
);

ALTER TABLE bundle_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bundle_version_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE bundle_version_object_class_capability (
    id integer NOT NULL,
    bundle_version_id integer NOT NULL,
    object_class character varying(255),
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[]
);

ALTER TABLE bundle_version_object_class_capability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bundle_version_object_class_capability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE request (
    id integer NOT NULL,
    application_id uuid NOT NULL,
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[] NOT NULL,
    requester character varying(255),
    mail character varying(50),
    collab boolean NOT NULL,
    base_url character varying(255),
    system_version character varying(20),
    CONSTRAINT unique_request_per_application UNIQUE (application_id)
);

ALTER TABLE request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE object_class_capabilities (
    id integer NOT NULL,
    request_id integer NOT NULL,
    object_name character varying(30) NOT NULL,
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[] NOT NULL
);

ALTER TABLE object_class_capabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME object_class_capabilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE votes (
    request_id integer NOT NULL,
    voter character varying(255) NOT NULL
);

CREATE TABLE integration_kind (
    identifier character varying(64) NOT NULL,
    display_name character varying(255) NOT NULL,
    description character varying(255),
    generic_application_id uuid,
    custom_connectors IntegrationMethodType[] DEFAULT '{}'::IntegrationMethodType[]
);

CREATE TABLE integration (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    kind_id character varying(64) NOT NULL,
    description character varying(255),
    documentation_link character varying(255),
    link_sample text[],
    system_version character varying(255)
);

CREATE TABLE integration_implementation (
    integration_id uuid NOT NULL,
    implementation_id uuid NOT NULL
);

CREATE TABLE integration_object_class_capability (
    integration_id uuid NOT NULL,
    object_class character varying(255) NOT NULL,
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[]
);

CREATE TABLE recently_used_applications (
    id             bigint NOT NULL,
    user_id        character varying(255) NOT NULL,
    application_id uuid NOT NULL
);

ALTER TABLE recently_used_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recently_used_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE organizations (
    id          integer NOT NULL,
    name        character varying(255) NOT NULL,
    description text
);

CREATE TABLE catalog_users (
    username        character varying(255) NOT NULL,
    password        character varying(255) NOT NULL,
    role            character varying(64)  NOT NULL,
    organization_id integer
);

-- end of region

-- region tables CONSTRAINTs

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT application_application_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT application_origin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application_tag
    ADD CONSTRAINT application_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY connid_version
    ADD CONSTRAINT connid_version_pkey PRIMARY KEY (version);

ALTER TABLE ONLY country_of_origin
    ADD CONSTRAINT country_of_origin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY downloads
    ADD CONSTRAINT downloads_pkey PRIMARY KEY (implementation_version_id, ip_address, downloaded_at);

ALTER TABLE ONLY implementation_implementation_tag
    ADD CONSTRAINT implementation_implementation_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY implementation
    ADD CONSTRAINT implementation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY implementation_tag
    ADD CONSTRAINT implementation_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY implementation_version
    ADD CONSTRAINT implementation_version_pkey PRIMARY KEY (id);

ALTER TABLE ONLY request
    ADD CONSTRAINT request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT unique_app_country UNIQUE (application_id, country_id);

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT unique_app_tag UNIQUE (application_id, tag_id);

ALTER TABLE ONLY connector_bundle
    ADD CONSTRAINT connector_bundle_pkey PRIMARY KEY (id);

ALTER TABLE ONLY bundle_version
    ADD CONSTRAINT bundle_version_pkey PRIMARY KEY (id);

ALTER TABLE ONLY bundle_version_object_class_capability
    ADD CONSTRAINT bundle_version_object_class_capability_pkey PRIMARY KEY (id);

ALTER TABLE ONLY integration
    ADD CONSTRAINT integration_pkey PRIMARY KEY (id);

ALTER TABLE ONLY integration_implementation
    ADD CONSTRAINT integration_implementation_pkey PRIMARY KEY (integration_id, implementation_id);

ALTER TABLE ONLY integration_object_class_capability
    ADD CONSTRAINT integration_occ_pkey PRIMARY KEY (integration_id, object_class);

ALTER TABLE ONLY integration_kind
    ADD CONSTRAINT integration_kind_pkey PRIMARY KEY (identifier);

ALTER TABLE ONLY object_class_capabilities
    ADD CONSTRAINT object_class_capabilities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY votes
    ADD CONSTRAINT votes_pkey PRIMARY KEY (request_id, voter);

CREATE INDEX idx_dl_ver ON downloads USING btree (implementation_version_id);

CREATE INDEX idx_impl_app ON implementation USING btree (application_id);

CREATE INDEX idx_implver_bver ON implementation_version USING btree (bundle_version_id);

CREATE INDEX idx_req_app ON request USING btree (application_id);

CREATE INDEX IF NOT EXISTS ix_implver_capabilities_gin ON implementation_version USING gin (capabilities);

CREATE INDEX IF NOT EXISTS ix_request_capabilities_gin ON request USING gin (capabilities);

CREATE INDEX idx_impl_bundle ON implementation USING btree (connector_bundle_id);

CREATE INDEX idx_bver_bundle ON bundle_version USING btree (connector_bundle_id);

CREATE INDEX idx_bver_connid ON bundle_version USING btree (connid_version);

CREATE INDEX idx_implver_impl ON implementation_version USING btree (implementation_id);

CREATE UNIQUE INDEX uq_bvoc_ver_class ON bundle_version_object_class_capability (bundle_version_id, object_class) WHERE object_class IS NOT NULL;

CREATE UNIQUE INDEX uq_bvoc_ver_null_class ON bundle_version_object_class_capability (bundle_version_id) WHERE object_class IS NULL;

CREATE INDEX idx_bvoc_bver ON bundle_version_object_class_capability USING btree (bundle_version_id);

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT fk_app_origin_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY application_origin
    ADD CONSTRAINT fk_app_origin_country FOREIGN KEY (country_id) REFERENCES country_of_origin(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT fk_app_tag_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY application_application_tag
    ADD CONSTRAINT fk_app_tag_tag FOREIGN KEY (tag_id) REFERENCES application_tag(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY downloads
    ADD CONSTRAINT fk_dl_implver FOREIGN KEY (implementation_version_id) REFERENCES implementation_version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY implementation
    ADD CONSTRAINT fk_impl_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY implementation
    ADD CONSTRAINT fk_impl_bundle FOREIGN KEY (connector_bundle_id) REFERENCES connector_bundle(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY implementation_implementation_tag
    ADD CONSTRAINT fk_impl_tag_impl FOREIGN KEY (implementation_id) REFERENCES implementation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY implementation_implementation_tag
    ADD CONSTRAINT fk_impl_tag_tag FOREIGN KEY (tag_id) REFERENCES implementation_tag(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY bundle_version
    ADD CONSTRAINT fk_bver_bundle FOREIGN KEY (connector_bundle_id) REFERENCES connector_bundle(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY bundle_version
    ADD CONSTRAINT fk_bver_connid FOREIGN KEY (connid_version) REFERENCES connid_version(version) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY implementation_version
    ADD CONSTRAINT fk_implver_bver FOREIGN KEY (bundle_version_id) REFERENCES bundle_version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY request
    ADD CONSTRAINT fk_request_app FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY object_class_capabilities
    ADD CONSTRAINT fk_objcap_request FOREIGN KEY (request_id) REFERENCES request(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY votes
    ADD CONSTRAINT fk_votes_request FOREIGN KEY (request_id) REFERENCES request(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY implementation_version
    ADD CONSTRAINT fk_implver_impl FOREIGN KEY (implementation_id) REFERENCES implementation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY bundle_version_object_class_capability
    ADD CONSTRAINT fk_bvoc_bver FOREIGN KEY (bundle_version_id) REFERENCES bundle_version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration
    ADD CONSTRAINT fk_integration_kind FOREIGN KEY (kind_id) REFERENCES integration_kind(identifier) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_object_class_capability
    ADD CONSTRAINT fk_intocc_integration FOREIGN KEY (integration_id) REFERENCES integration(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_implementation
    ADD CONSTRAINT fk_intimpl_integration FOREIGN KEY (integration_id) REFERENCES integration(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_implementation
    ADD CONSTRAINT fk_intimpl_implementation FOREIGN KEY (implementation_id) REFERENCES implementation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY integration_kind
    ADD CONSTRAINT fk_intkind_app FOREIGN KEY (generic_application_id) REFERENCES application(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY recently_used_applications
    ADD CONSTRAINT recently_used_applications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recently_used_applications
    ADD CONSTRAINT uq_rua_user_app UNIQUE (user_id, application_id);

ALTER TABLE ONLY recently_used_applications
    ADD CONSTRAINT fk_rua_application FOREIGN KEY (application_id) REFERENCES application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog_users
    ADD CONSTRAINT catalog_users_pkey PRIMARY KEY (username);

ALTER TABLE ONLY catalog_users
    ADD CONSTRAINT fk_catalog_users_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- end of region