/*
 * Copyright (C) 2010-2025 Evolveum and contributors
 *
 * This work is dual-licensed under the Apache License 2.0
 * and European Union Public License. See LICENSE file for details.
 */
 
 CREATE TYPE ApplicationLifecycleType AS ENUM (
	'REQUESTED',
	'IN_PUBLISH_PROCESS',
	'ACTIVE',
	'WITH_ERROR'
);

CREATE TYPE ApplicationTagType AS ENUM (
	'DEPLOYMENT',
	'LOCALITY',
	'CATEGORY',
	'COMMON'
);

CREATE TYPE FrameworkType AS ENUM (
	'CONNID',
	'SCIM_REST'
);

CREATE TYPE LicenseType AS ENUM (
	'MIT',
	'APACHE_2',
	'BSD',
	'EUPL'
);

CREATE TYPE ImplementationVersionLifecycleType AS ENUM (
	'IN_PUBLISH_PROCESS',
	'ACTIVE',
	'DEPRECATED',
	'ARCHIVED',
	'WITH_ERROR'
);

CREATE TYPE BuildFrameworkType AS ENUM (
	'MAVEN',
	'GRADLE'
);

CREATE TYPE "CapabilityType" AS ENUM (
    'CREATE',
	'GET',
	'UPDATE',
	'DELETE',
	'TEST',
	'SCRIPT_ON_CONNECTOR',
	'SCRIPT_ON_RESOURCE',
	'AUTHENTICATION',
	'SEARCH',
	'VALIDATE',
	'SYNC',
	'LIVE_SYNC',
	'SCHEMA',
	'DISCOVER_CONFIGURATION',
	'RESOLVE_USERNAME',
	'PARTIAL_SCHEMA',
	'COMPLEX_UPDATE_DELTA',
	'UPDATE_DELTA'
);
-- end of region

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';

SET default_tablespace = '';

SET default_table_access_method = heap;

-- region ID-pool table

CREATE TABLE public.application (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	name character varying(255),
	display_name character varying(255),
	description character varying(255),
	logo bytea,
	lifecycle_state ApplicationLifecycleType NOT NULL,
	created_at timestamp without time zone NOT NULL,
	last_modified timestamp without time zone NOT NULL
);

CREATE TABLE public.application_application_tag (
    id bigint NOT NULL,
    application_id uuid NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE public.application_application_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_application_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.application_origin (
    id bigint NOT NULL,
    application_id uuid NOT NULL,
    country_id integer NOT NULL
);

ALTER TABLE public.application_origin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_origin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.application_tag (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL,
    tag_type ApplicationTagType NOT NULL
);

ALTER TABLE public.application_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.connid_version (
    version character varying(64) NOT NULL,
    midpoint_version character varying(255) NOT NULL
);

CREATE TABLE public.country_of_origin (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL
);

ALTER TABLE public.country_of_origin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_of_origin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.downloads (
    implementation_version_id uuid NOT NULL,
    ip_address character varying(45) NOT NULL,
    user_agent character varying(255) NOT NULL,
    downloaded_at timestamp without time zone NOT NULL,
    id uuid NOT NULL
);

CREATE TABLE public.implementation (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name character varying(255),
    connector_bundle character varying(255),
    maintainer character varying(255),
	framework FrameworkType NOT NULL,
    ticketing_system_link text,
	license LicenseType NOT NULL,
    application_id uuid NOT NULL
);

CREATE TABLE public.implementation_implementation_tag (
    id integer NOT NULL,
    implementation_id uuid NOT NULL,
    tag_id integer NOT NULL
);

ALTER TABLE public.implementation_implementation_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.implementation_implementation_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.implementation_tag (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    display_name character varying(255) NOT NULL
);

ALTER TABLE public.implementation_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.implementation_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.implementation_version (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    description character varying(255),
    connector_version character varying(255),
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[] NOT NULL,
    browse_link character varying(255),
    checkout_link character varying(255),
    download_link character varying(255),
    system_version character varying(255),
    author character varying(255),
    released_date date,
    publish_date timestamp without time zone,
    lifecycle_state ImplementationVersionLifecycleType NOT NULL,
    build_framework BuildFrameworkType NOT NULL,
    connid_version character varying(64),
    implementation_id uuid NOT NULL,
    error_message character varying(255)
);

CREATE TABLE public.request (
    id integer NOT NULL,
    application_id uuid NOT NULL,
    capabilities "CapabilityType"[] DEFAULT '{}'::"CapabilityType"[] NOT NULL,
    requester character varying(255),
    CONSTRAINT unique_request_per_application UNIQUE (application_id)
);

ALTER TABLE public.request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.votes (
    request_id integer NOT NULL,
    voter character varying(255) NOT NULL
);

-- end of region

-- region tables CONSTRAINTs

ALTER TABLE ONLY public.application_application_tag
    ADD CONSTRAINT application_application_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.application_origin
    ADD CONSTRAINT application_origin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.application_tag
    ADD CONSTRAINT application_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.connid_version
    ADD CONSTRAINT connid_version_pkey PRIMARY KEY (version);

ALTER TABLE ONLY public.country_of_origin
    ADD CONSTRAINT country_of_origin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.downloads
    ADD CONSTRAINT downloads_pkey PRIMARY KEY (implementation_version_id, ip_address, downloaded_at);

ALTER TABLE ONLY public.implementation_implementation_tag
    ADD CONSTRAINT implementation_implementation_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.implementation
    ADD CONSTRAINT implementation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.implementation_tag
    ADD CONSTRAINT implementation_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.implementation_version
    ADD CONSTRAINT implementation_version_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.request
    ADD CONSTRAINT request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.application_origin
    ADD CONSTRAINT unique_app_country UNIQUE (application_id, country_id);

ALTER TABLE ONLY public.application_application_tag
    ADD CONSTRAINT unique_app_tag UNIQUE (application_id, tag_id);

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT votes_pkey PRIMARY KEY (request_id, voter);

CREATE INDEX idx_dl_ver ON public.downloads USING btree (implementation_version_id);

CREATE INDEX idx_impl_app ON public.implementation USING btree (application_id);

CREATE INDEX idx_implver_connid ON public.implementation_version USING btree (connid_version);

CREATE INDEX idx_implver_impl ON public.implementation_version USING btree (implementation_id);

CREATE INDEX idx_req_app ON public.request USING btree (application_id);

CREATE INDEX IF NOT EXISTS ix_implver_capabilities_gin ON public.implementation_version USING gin (capabilities);

CREATE INDEX IF NOT EXISTS ix_request_capabilities_gin ON public.request USING gin (capabilities);

ALTER TABLE ONLY public.application_origin
    ADD CONSTRAINT fk_app_origin_app FOREIGN KEY (application_id) REFERENCES public.application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.application_origin
    ADD CONSTRAINT fk_app_origin_country FOREIGN KEY (country_id) REFERENCES public.country_of_origin(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.application_application_tag
    ADD CONSTRAINT fk_app_tag_app FOREIGN KEY (application_id) REFERENCES public.application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.application_application_tag
    ADD CONSTRAINT fk_app_tag_tag FOREIGN KEY (tag_id) REFERENCES public.application_tag(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.downloads
    ADD CONSTRAINT fk_dl_implver FOREIGN KEY (implementation_version_id) REFERENCES public.implementation_version(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.implementation
    ADD CONSTRAINT fk_impl_app FOREIGN KEY (application_id) REFERENCES public.application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.implementation_implementation_tag
    ADD CONSTRAINT fk_impl_tag_impl FOREIGN KEY (implementation_id) REFERENCES public.implementation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.implementation_implementation_tag
    ADD CONSTRAINT fk_impl_tag_tag FOREIGN KEY (tag_id) REFERENCES public.implementation_tag(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.implementation_version
    ADD CONSTRAINT fk_implver_connid FOREIGN KEY (connid_version) REFERENCES public.connid_version(version) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.implementation_version
    ADD CONSTRAINT fk_implver_impl FOREIGN KEY (implementation_id) REFERENCES public.implementation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.request
    ADD CONSTRAINT fk_request_app FOREIGN KEY (application_id) REFERENCES public.application(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT fk_votes_request FOREIGN KEY (request_id) REFERENCES public.request(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

-- end of region