--
-- Copyright (c) 2010-2025 Evolveum and contributors
--
-- Licensed under the EUPL-1.2 or later.
--

-- Cumulative database upgrade script.
--
-- Contains one apply_change section per schema change; every new schema change is
-- APPENDED here as a new section. The current change number is stored in the
-- m_global_metadata table under the 'schemaChangeNumber' key - the same mechanism as
-- midPoint's native repository (postgres.sql / postgres-upgrade.sql). The table and the
-- apply_change procedure are created by config/sql/01_schema.sql.
--
-- Always re-run the WHOLE file against an existing database:
--
--   psql -v ON_ERROR_STOP=1 -U integration_catalog -d integration_catalog -f config/sql/upgrade/upgrade.sql
--
-- It is safe to run this script repeatedly: apply_change(N, ...) executes only when the
-- stored change number is lower than N, so already-applied sections are skipped and only
-- the new ones take effect. The SQL inside apply_change does NOT have to be idempotent.
--
-- Use plain psql, NOT tools with their own transaction handling (pgAdmin): apply_change
-- COMMITs internally, which fails inside a wrapping transaction block. For the same
-- reason never put an explicit COMMIT inside a change. If a later statement depends on
-- an earlier one being committed (typically ALTER TYPE ... ADD VALUE followed by a use
-- of the new value), split them into two apply_change calls.
--
-- Fresh installations do not need this file: config/sql/01_schema.sql already creates
-- the schema at the current change number.

DO $$
    BEGIN
        if to_regproc('apply_change') is null then
            raise exception 'You are running the UPGRADE script, but the procedure ''apply_change'' is missing.
Are you sure you are running this upgrade script on the correct database?
Current database name is ''%'', schema name is ''%''.', current_database(), current_schema();
        end if;
    END
$$;

-- region change 2: connector.cloned_from
-- Records the original connector a copy-on-write clone was made from; the approve step
-- uses it to fold a same-version metadata edit back into the shared original connector.
-- (Change 1 is the baseline schema created by config/sql/01_schema.sql.)
call apply_change(2, $aa$
ALTER TABLE connector ADD COLUMN IF NOT EXISTS cloned_from integer;
$aa$);
-- end of region

-- region change 3: user data moved entirely to Keycloak - REVERTED, kept as a no-op
-- Change 3 originally dropped catalog_users and organizations, because task #11855 moved
-- authentication to Keycloak. That task was reverted, so the drop must not run any more:
-- a database still at change 2 would lose its user data on the way to change 4. The
-- number stays occupied so that already-applied installations keep a consistent history;
-- databases that did apply the original change 3 are repaired by change 4 below.
call apply_change(3, $aa$
SELECT 1;
$aa$);
-- end of region

-- region change 4: user, role and organization data live in the database again
-- Completes the revert of task #11855. Deliberately idempotent, because it has to end in
-- the same state from two different starting points: a database that never lost the
-- tables (stopped at change 2) and one where the original change 3 dropped them.
call apply_change(4, $aa$
CREATE TABLE IF NOT EXISTS organizations (
    id          integer NOT NULL,
    name        character varying(255) NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS catalog_users (
    username        character varying(255) NOT NULL,
    password        character varying(255) NOT NULL,
    role            character varying(64)  NOT NULL,
    organization_id integer
);

DO $$
    BEGIN
        if not exists (select 1 from pg_attribute
                        where attrelid = 'organizations'::regclass
                          and attname = 'id'
                          and attidentity <> '') then
            ALTER TABLE organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
                SEQUENCE NAME organizations_id_seq
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1
            );
        end if;

        if not exists (select 1 from pg_constraint where conname = 'organizations_pkey') then
            ALTER TABLE ONLY organizations
                ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);
        end if;

        if not exists (select 1 from pg_constraint where conname = 'catalog_users_pkey') then
            ALTER TABLE ONLY catalog_users
                ADD CONSTRAINT catalog_users_pkey PRIMARY KEY (username);
        end if;

        if not exists (select 1 from pg_constraint where conname = 'fk_catalog_users_org') then
            ALTER TABLE ONLY catalog_users
                ADD CONSTRAINT fk_catalog_users_org FOREIGN KEY (organization_id)
                REFERENCES organizations(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
        end if;
    END
$$;

CREATE INDEX IF NOT EXISTS idx_catalog_users_org_id ON catalog_users USING btree (organization_id);

-- Test users and organizations, same set as config/sql/02_data.sql. ON CONFLICT keeps
-- existing rows untouched on a database that still had its own user data.
INSERT INTO organizations (id, name, description) VALUES
	(1, 'Acme co.', 'Test organization for OrganizationContributor and IndividualContributor users'),
	(2, 'Evolveum', 'Evolveum — application administrators')
ON CONFLICT (id) DO NOTHING;

SELECT setval('organizations_id_seq', greatest((select max(id) from organizations), 1));

INSERT INTO catalog_users (username, password, role, organization_id) VALUES
	('u1', crypt('u1', gen_salt('bf', 10)), 'OrganizationContributor', 1),
	('u2', crypt('u2', gen_salt('bf', 10)), 'ReadOnly',                NULL),
	('u3', crypt('u3', gen_salt('bf', 10)), 'IndividualContributor',   NULL),
	('u4', crypt('u4', gen_salt('bf', 10)), 'IndividualContributor',   1),
	('u5', crypt('u5', gen_salt('bf', 10)), 'Superuser',               2)
ON CONFLICT (username) DO NOTHING;
$aa$);
-- end of region

-- Append new apply_change sections above this line. For every new change N (3 and higher):
--   1. add a "-- region change N: <name>" section here containing
--        call apply_change(N, $aa$
--        <any SQL, does not have to be idempotent>
--        $aa$);
--      ($aa$ dollar-quoting keeps inner $$ function bodies intact; the procedure
--      advances 'schemaChangeNumber' in m_global_metadata and commits by itself),
--   2. make the same change in config/sql/01_schema.sql and bump the number in the
--      "call apply_change" at the end of that script to N,
--   3. bump REQUIRED_VERSION in DatabaseSchemaVersionValidator to N.
